spring:
  datasource:
    url: jdbc:postgresql://localhost:5480/task_db
    username: postgres
    password: 111Zorro222!
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/tms

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: task_service
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
